Added edit user, change password pages with full functionality and he…
SergeyGhazaryan/GTA-Versions pull request #6
Opened 2021-07-03 12:23 UTC by SergeyGhazaryan

…ader

2021-07-03 14:18 UTC, ArayikHovhannisyan requested changes
Header should be used in one place, at the top of the program, not imported in every page.

2021-07-03 14:18 UTC, arayik-99 commented on api/src/GTAVersions.Domain/GTAVersions.Domain.csproj
> +    <PackageReference Include="Microsoft.AspNet.Identity.EntityFramework" Version="2.2.3" />
Why do we need this?

2021-07-03 14:18 UTC, arayik-99 commented on api/src/GTAVersions.Domain/Services/AuthService.cs
> +            var token = await _userService.UpdateAndReturnUserToken(userDTO);
Why was the name changed?

2021-07-03 14:18 UTC, arayik-99 commented on api/src/GTAVersions.Domain/Services/UserService.cs
> +
Redudant line.

2021-07-03 14:18 UTC, arayik-99 commented on api/src/GTAVersions.Domain/Services/UserService.cs
> +
Redudant line.

2021-07-03 14:18 UTC, arayik-99 commented on api/src/GTAVersions.Domain/Services/AuthService.cs
> +
Redudant line.

2021-07-03 14:18 UTC, arayik-99 commented on api/src/GTAVersions.Domain/Services/AuthService.cs
> +
Redudant line.

2021-07-03 14:18 UTC, ArayikHovhannisyan commented on api/src/GTAVersions.Domain/Services/AuthService.cs
> +
Redudant line.

2021-07-03 14:18 UTC, ArayikHovhannisyan commented on api/src/GTAVersions/Controllers/AuthController.cs
> +        [HttpPut("settings")]
Rename this changePassword and change method to PATCH (Read difference between PUT and PATCH)

2021-07-03 14:18 UTC, ArayikHovhannisyan commented on api/src/GTAVersions/Controllers/UserController.cs
> +
Redudant line.

2021-07-03 14:18 UTC, ArayikHovhannisyan commented on api/src/GTAVersions/Controllers/UserController.cs
> +
Redudant line.

2021-07-03 14:20 UTC, SergeyGhazaryan commented on api/src/GTAVersions.Domain/Services/AuthService.cs
> +            var token = await _userService.UpdateAndReturnUserToken(userDTO);
Multiple places with async, multiple places without async. I decided to remove them.

2021-07-03 17:59 UTC, Shitikyan commented on api/src/GTAVersions.Data/Interfaces/IUserRepository.cs
> +        Task<User> EditUser(string firstName, string lastName, string username, int id);
make id as first parameter

2021-07-03 17:59 UTC, Shitikyan commented on api/src/GTAVersions.Data/Repositories/UserRepository.cs
> +            var query = "INSERT INTO Users (FirstName, LastName, Username, PasswordHash) OUTPUT INSERTED.Id VALUES (@FirstName, @LastName, @Username, @PasswordHash)";
no need @PasswordHash for output

2021-07-03 18:01 UTC, Shitikyan commented on api/src/GTAVersions.Domain/Interfaces/IUserService.cs
> +        Task<UserDTO> EditUser(EditUserDTO editUserDTO, string currentUserId);
why user id is string?

2021-07-03 18:01 UTC, Shitikyan commented on api/src/GTAVersions.Domain/Interfaces/IUserService.cs
> +        Task<UserDTO> EditUser(EditUserDTO editUserDTO, string currentUserId);
make it as first param

2021-07-03 18:03 UTC, Shitikyan commented on gta-gallery/src/components/changePassword/index.jsx
> +      <Header />
not correct behavior of using Header

2021-07-03 18:03 UTC, Shitikyan commented on gta-gallery/src/components/editUser/index.jsx
> +      <Header />
not correct behavior of using Header

2021-07-03 18:03 UTC, Shitikyan commented on gta-gallery/src/components/gtaVersionDetails/index.jsx
> +      <Header />
not correct behavior of using Header

2021-07-03 18:04 UTC, Shitikyan commented on gta-gallery/src/layout/index.jsx
> +      <Header />
not correct behavior of using Header

2021-07-06 08:01 UTC, ArayikHovhannisyan requested changes

2021-07-06 08:01 UTC, arayik-99 commented on api/src/GTAVersions/Controllers/UserController.cs
> +        public async Task<IActionResult> GetCurrentUser()
Move this method upper. The controllers are usually in this order - GET, POST, PUT/PATCH, DELETE

2021-07-06 08:01 UTC, arayik-99 commented on gta-gallery/src/components/header/index.jsx
> +import { Menu, Dropdown } from 'antd';
Move this up

2021-07-06 08:01 UTC, arayik-99 commented on gta-gallery/src/components/header/index.jsx
> +import { isEmpty } from 'lodash';
move this after react-redux

2021-07-06 08:01 UTC, arayik-99 commented on gta-gallery/src/components/login/index.jsx
>  import { NavLink } from 'react-router-dom';
Merge this import with the upper import (2 line)

2021-07-06 08:01 UTC, arayik-99 commented on gta-gallery/src/components/editUser/index.jsx
> +import { useHistory } from 'react-router-dom';
Move up

2021-07-06 08:01 UTC, ArayikHovhannisyan commented on gta-gallery/src/services/axiosInstance.js
> +  if (token) {
remove curly braces

2021-07-06 17:11 UTC, Karen-Avdalyan requested changes

2021-07-06 17:11 UTC, Karen-Avdalyan commented on gta-gallery/src/components/gtaVersionDetails/index.jsx
> +      clearState();
you can call this method in closeModal function

2021-07-06 17:11 UTC, Karen-Avdalyan commented on gta-gallery/src/components/gtaVersionDetails/index.jsx
> +      let newVersions = gtaVersionDetails;
this row is redundant

2021-07-06 17:11 UTC, Karen-Avdalyan commented on gta-gallery/src/components/shared/addVersionModal/addVersionModal.jsx
> +  onOk,
this prop name is not correct I think

2021-07-06 17:11 UTC, Karen-Avdalyan commented on gta-gallery/src/components/shared/updateVersionModal/updateVersionModal.jsx
> +  onOk,
this prop name is not correct I think

2021-07-07 16:17 UTC, ArayikHovhannisyan requested changes

2021-07-07 16:17 UTC, ArayikHovhannisyan commented on gta-gallery/src/layout/index.jsx
>  import { getAllVersions, createVersion, deleteVersion } from '../services';
move this at the end of imports. Make sure everywhere it's imported the same.

2021-07-07 16:17 UTC, ArayikHovhannisyan commented on gta-gallery/src/components/modal.jsx
> +  imageValue = '',
Why do we have default value here?

2021-07-07 16:23 UTC, SergeyGhazaryan commented on gta-gallery/src/components/modal.jsx
> +  imageValue = '',
To show a picture when needed.

2021-07-07 16:59 UTC, ArayikHovhannisyan approved these changes

2021-07-07 17:15 UTC, merged